package com.anews.model

import kotlinx.datetime.LocalDate

val mockArticles = listOf(
    Article(
        id = "1",
        title = "Android Bench: Google's Public LLM Leaderboard",
        summary = "Google launched Android Bench, the first public benchmark that scores LLMs specifically on Android tasks: resolving breaking API changes, domain-specific Wear OS challenges, and real-world developer workflows across the Android ecosystem.",
        url = "https://android-developers.googleblog.com",
        sourceLabel = "android-developers.googleblog",
        sourceDomain = "android-developers.googleblog.com",
        category = Category.AI,
        date = LocalDate(2026, 3, 15),
        readTimeMinutes = 5,
    ),
    Article(
        id = "2",
        title = "Android Studio Panda 2: Prompt → Deployed App",
        summary = "The new 'Create with AI' flow takes a text description plus optional screenshots, produces a full project plan to review, then generates a complete runnable app. Panda 2 also ships a redesigned device manager and faster build cache invalidation.",
        url = "https://android-developers.googleblog.com",
        sourceLabel = "android-developers.googleblog",
        sourceDomain = "android-developers.googleblog.com",
        category = Category.AI,
        date = LocalDate(2026, 3, 4),
        readTimeMinutes = 4,
    ),
    Article(
        id = "3",
        title = "Compose Multiplatform for Web Goes Beta",
        summary = "Compose Multiplatform 1.9.0 moves web (Wasm) from Alpha to Beta. The web target now ships Material 3, adaptive layouts, browser navigation (back/forward, deep links, history), and a canvas renderer that matches desktop fidelity.",
        url = "https://blog.jetbrains.com",
        sourceLabel = "blog.jetbrains",
        sourceDomain = "blog.jetbrains.com",
        category = Category.Compose,
        date = LocalDate(2026, 2, 20),
        readTimeMinutes = 6,
    ),
    Article(
        id = "4",
        title = "Compose Multiplatform 1.10.0: Navigation 3 + Stable Hot Reload",
        summary = "Navigation 3 lands as stable API with type-safe routes, nested graphs, and a shared-element transition system. Hot reload is now stable on all JVM targets — change a composable and see it update without restarting the process.",
        url = "https://blog.jetbrains.com",
        sourceLabel = "blog.jetbrains",
        sourceDomain = "blog.jetbrains.com",
        category = Category.Compose,
        date = LocalDate(2026, 1, 10),
        readTimeMinutes = 7,
    ),
    Article(
        id = "5",
        title = "Update Your Kotlin Projects for Android Gradle Plugin 9.0",
        summary = "AGP 9.0 drops support for Groovy build scripts, requires Kotlin 2.0+, and enforces strict variant-aware dependency resolution. The migration guide covers the most common breakages and how the new declarative Gradle DSL replaces imperative configuration blocks.",
        url = "https://kotlinlang.org",
        sourceLabel = "kotlinlang.org",
        sourceDomain = "kotlinlang.org",
        category = Category.Kotlin,
        date = LocalDate(2026, 3, 1),
        readTimeMinutes = 8,
    ),
    Article(
        id = "6",
        title = "Kotlin 2.2 Brings Context Parameters and Guard Conditions",
        summary = "Context parameters replace the old context receivers experiment and are now stable. Guard conditions in when expressions allow complex pattern matching without nesting. The compiler also ships a new default IR backend that cuts compile times by up to 30% on large projects.",
        url = "https://kotlinlang.org",
        sourceLabel = "kotlinlang.org",
        sourceDomain = "kotlinlang.org",
        category = Category.Kotlin,
        date = LocalDate(2026, 2, 5),
        readTimeMinutes = 5,
    ),
)
